name: daily
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub contribution grid snake animation
        uses: Platane/snk@v2.1.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
