name: daily
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub contribution grid snake animation
        uses: Platane/snk@v2.1.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg

      - name: Push generated animation to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
