name: daily
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 16 * * *"
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub contribution grid snake animation
        uses: Platane/snk@v2.2.1
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg

      - name: Upload animation as an artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: animation
          path: dist/

      - name: Push generated animation to output branch
        if: github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
